app:
  name: archetype
  version: "1.0.0"
  base-path: /api

swagger:
  title: Archetype-Spring-mvc
  description: archetype for projects usring Spring MVC
  version: "1.0.0"


spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher